[versions]
agp = "8.12.2"
bom = "3.2.3"
coil = "2.4.0"
datastorePreferences = "1.2.0"
glance = "1.1.1"
hiltNavigationCompose = "1.3.0"
jsoup = "1.21.2"
kotlin = "2.2.10"
ksp = "2.2.10-2.0.2"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
ktorClientCio = "3.3.0"
ktorClientContentNegotiation = "3.3.0"
ktorClientCore = "3.3.0"
ktorClientLogging = "3.3.0"
lifecycleRuntimeKtx = "2.9.3"
composeBom = "2025.08.01"
lifecycle="2.9.3"
hilt = "2.57.1"
napier = "2.7.1"
nav3Core = "1.0.0"
lifecycleViewmodelNav3 = "2.10.0"
room = "2.8.0"
kotlinSerialization = "1.9.0"
appcompat = "1.7.1"
material = "1.13.0"
javaxInject = "1"
firebaseCrashlytics = "20.0.2"
googleGmsGoogleServices = "4.4.3"
googleFirebaseCrashlytics = "3.0.6"
appcompatVersion = "1.7.1"
materialVersion = "1.13.0"
velo = "0.2.0"
materialIcon="1.7.8"
androidxAppcompat = "1.7.1"
googleMaterial = "1.13.0"
constraintlayout = "1.1.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-glance-appwidget-preview = { module = "androidx.glance:glance-appwidget-preview", version.ref = "glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-glance-preview = { module = "androidx.glance:glance-preview", version.ref = "glance" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIcon" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorClientCio" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientContentNegotiation" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorClientLogging" }

navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
navigation3-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }

napier = { module = "io.github.aakira:napier", version.ref = "napier" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }

superbase-bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "bom" }
superbase-postgrest = { module = "io.github.jan-tennert.supabase:postgrest-kt" }

javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }

android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

velo-core = { group = "io.github.hyunjine", name = "velo-core", version.ref = "velo" }
velo-android = { group = "io.github.hyunjine", name = "velo-android", version.ref = "velo" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }

constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout" }

[bundles]
room = [
    "androidx-room-compiler",
    "androidx-room-ktx",
    "androidx-room-runtime"
]
glance = [
    "androidx-glance-appwidget",
    "androidx-glance-appwidget-preview",
    "androidx-glance-material3",
    "androidx-glance-preview"
]

[plugins]
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlytics" }

# custom plugin
feature = { id = "feature.plugin" }
bundle-compose = { id = "compose.plugin" }
bundle-hilt = { id = "hilt.plugin" }
bundle-serialization = { id = "serialization.plugin" }
